[package]
name = "slint-rust-template"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
resvg = "0.47.0"
rfd = "0.17.2"
slint = { version = "1.14.1", features = ["renderer-skia"] }
esvg-rs = { path = "vendor/esvg-rs" }

[build-dependencies]
slint-build = "=1.14.1"

[profile.release]
codegen-units = 1
lto = true
strip = true
