import { ScrollView } from "std-widgets.slint";
import { SidebarPanelHeader, SidebarPanelContent } from "./sidebar-panel.slint";
import { AppState } from "../app-state.slint";
import { NSwitch } from "../components/switch.slint";

export component PluginsPanel inherits VerticalLayout {
  SidebarPanelHeader {
    label: "Plugins";
  }

  SidebarPanelContent {
    VerticalLayout {
      spacing: 10px;
      alignment: start;

      NSwitch {
        text: "Apply Transforms";
        checked <=> AppState.plugin-apply-transforms;
        enabled: AppState.svg-loaded;
        toggled => {
          AppState.request-optimize();
        }
      }

      NSwitch {
        text: "Collapse Groups";
        checked <=> AppState.plugin-collapse-groups;
        enabled: AppState.svg-loaded;
        toggled => {
          AppState.request-optimize();
        }
      }

      NSwitch {
        text: "Combine Paths";
        checked <=> AppState.plugin-combine-paths;
        enabled: AppState.svg-loaded;
        toggled => {
          AppState.request-optimize();
        }
      }

      NSwitch {
        text: "CSS to Attributes";
        checked <=> AppState.plugin-css-to-attributes;
        enabled: AppState.svg-loaded;
        toggled => {
          AppState.request-optimize();
        }
      }

      NSwitch {
        text: "Mangle IDs";
        checked <=> AppState.plugin-mangle-ids;
        enabled: AppState.svg-loaded;
        toggled => {
          AppState.request-optimize();
        }
      }

      NSwitch {
        text: "Number Precision";
        checked <=> AppState.plugin-number-precision;
        enabled: AppState.svg-loaded;
        toggled => {
          AppState.request-optimize();
        }
      }

      NSwitch {
        text: "Optimize Colors";
        checked <=> AppState.plugin-optimize-colors;
        enabled: AppState.svg-loaded;
        toggled => {
          AppState.request-optimize();
        }
      }

      NSwitch {
        text: "Remove Empty Text";
        checked <=> AppState.plugin-remove-empty-text;
        enabled: AppState.svg-loaded;
        toggled => {
          AppState.request-optimize();
        }
      }

      NSwitch {
        text: "Remove Unnecessary Attrs";
        checked <=> AppState.plugin-remove-unnecessary-attrs;
        enabled: AppState.svg-loaded;
        toggled => {
          AppState.request-optimize();
        }
      }

      NSwitch {
        text: "Remove Unnecessary Clip Paths";
        checked <=> AppState.plugin-remove-unnecessary-clip-paths;
        enabled: AppState.svg-loaded;
        toggled => {
          AppState.request-optimize();
        }
      }

      NSwitch {
        text: "Shape to Path";
        checked <=> AppState.plugin-shape-to-path;
        enabled: AppState.svg-loaded;
        toggled => {
          AppState.request-optimize();
        }
      }

      NSwitch {
        text: "Simplify Paths";
        checked <=> AppState.plugin-simplify-paths;
        enabled: AppState.svg-loaded;
        toggled => {
          AppState.request-optimize();
        }
      }

      NSwitch {
        text: "Sort Attrs";
        checked <=> AppState.plugin-sort-attrs;
        enabled: AppState.svg-loaded;
        toggled => {
          AppState.request-optimize();
        }
      }
    }
  }
}
