import { Palette } from "std-widgets.slint";  

export component SidebarPanelHeader inherits Rectangle {
  in property <string> label;

  background: Palette.control-background;

  HorizontalLayout {
    alignment: start;
    padding-top: 5px;
    padding-bottom: 5px;
    padding-left: 10px;
    padding-right: 10px;

    Text {
      text: label;
    }
  }
}

export component SidebarPanelContent inherits VerticalLayout {
  padding: 10px;
  alignment: start;
}
